use_gpu: true

model:
    name: DeepSpeech
    rnn_hidden_size: 768
    nb_layers: 5
    rnn_type: nn.LSTM
    bidirectional: true
    context: 20
    checkpoint: null
    save_dir: checkpoints/base
train:
    seed: 2020
    dataset: DialectTranscriptionDatasetDialectIndex
    data_dir: data/dialect_transcription
    meta_data: config/dialect_transcription/data/trans_train.csv
    batch_size: 16
    lr: 0.001
    lr_step: 5
    num_workers: 4
    grad_clip: 5.
    optimizer: adam
    weight_decay: 0.0
    mom: 0.9
    end_epoch: 300
    print_freq: 20
    ita: 0.1
dev:
    dataset: DialectTranscriptionDatasetDialectIndex
    data_dir: data/dialect_transcription
    meta_data: config/dialect_transcription/data/trans_dev.csv
    print_freq: 500
test:
    dataset: DialectTranscriptionDatasetDialectIndex
    data_dir: data/dialect_transcription
    meta_data: config/dialect_transcription/data/trans_test.csv
    beam_size: 10
    print_freq: 500
feature:
    save_dir: data/dialect_transcription/stft
    sample_rate: 8000
    input_dim: 161
    window_size: 25
    stride: 5
    cmvn: true
    type: melspectrogram
data:
    label_dir: config/dialect_transcription/data/labels.json
    sample_size: 20000
    min_duration: 1
    PAD_token: 0
    SOS_token: 1
    EOS_token: 2
    vocab_size: 29
    num_dialect: 7
